INSERT INTO territories VALUES (54, 'Gregorytown', 2);
INSERT INTO territories VALUES (55, 'Angelamouth', 3);
INSERT INTO territories VALUES (56, 'Irwinside', 4);
INSERT INTO territories VALUES (57, 'Thompsonhaven', 1);
INSERT INTO territories VALUES (58, 'Newmanstad', 2);
INSERT INTO territories VALUES (59, 'Helentown', 3);
INSERT INTO territories VALUES (60, 'Samanthamouth', 3);
INSERT INTO territories VALUES (61, 'Arnoldmouth', 4);
INSERT INTO territories VALUES (62, 'Lewisview', 4);
INSERT INTO territories VALUES (63, 'Ryanville', 3);
INSERT INTO territories VALUES (64, 'North Markshire', 1);
INSERT INTO territories VALUES (65, 'Kellyport', 1);
INSERT INTO territories VALUES (66, 'Daviston', 1);
INSERT INTO territories VALUES (67, 'Christopherborough', 1);
INSERT INTO territories VALUES (68, 'Millerport', 1);
INSERT INTO territories VALUES (69, 'Arthurshire', 2);
INSERT INTO territories VALUES (70, 'Lake Patricia', 3);
INSERT INTO territories VALUES (71, 'Samanthamouth', 1);
INSERT INTO territories VALUES (72, 'Port Troy', 2);
INSERT INTO territories VALUES (73, 'East Latashastad', 3);
INSERT INTO territories VALUES (74, 'Johnsonhaven', 1);
INSERT INTO territories VALUES (75, 'Port Emilyborough', 3);
INSERT INTO territories VALUES (76, 'North Jesse', 2);
INSERT INTO territories VALUES (77, 'East Amandafort', 3);
INSERT INTO territories VALUES (78, 'Michaelland', 3);
INSERT INTO territories VALUES (79, 'Mendozachester', 3);
INSERT INTO territories VALUES (80, 'Lake Angelaburgh', 3);
INSERT INTO territories VALUES (81, 'Harrisstad', 3);
INSERT INTO territories VALUES (82, 'Duncanchester', 3);
INSERT INTO territories VALUES (83, 'New Ricky', 3);
INSERT INTO territories VALUES (84, 'Amberburgh', 2);
INSERT INTO territories VALUES (85, 'New Mary', 2);
INSERT INTO territories VALUES (86, 'East Mackenzie', 3);
INSERT INTO territories VALUES (87, 'Brianmouth', 3);
INSERT INTO territories VALUES (88, 'Whitebury', 3);
INSERT INTO territories VALUES (89, 'New Lisabury', 4);
INSERT INTO territories VALUES (90, 'Lake Michaelshire', 2);
INSERT INTO territories VALUES (91, 'South Karlastad', 4);
INSERT INTO territories VALUES (92, 'Bennettfurt', 3);
INSERT INTO territories VALUES (93, 'Lake Amyfort', 2);
INSERT INTO territories VALUES (94, 'Carlaland', 1);
INSERT INTO territories VALUES (95, 'West Annamouth', 1);
INSERT INTO territories VALUES (96, 'South Johnmouth', 3);
INSERT INTO territories VALUES (97, 'Port Parker', 1);
INSERT INTO territories VALUES (98, 'New Rebeccaberg', 2);
INSERT INTO territories VALUES (99, 'New Morganville', 3);
INSERT INTO territories VALUES (100, 'Victoriatown', 1);
INSERT INTO territories VALUES (101, 'North Amystad', 3);
INSERT INTO territories VALUES (102, 'Lake Taylorborough', 2);
INSERT INTO territories VALUES (103, 'Lake Chelseatown', 3);
INSERT INTO territories VALUES (104, 'Sarafurt', 3);
INSERT INTO territories VALUES (105, 'Josephbury', 3);
INSERT INTO territories VALUES (106, 'Davidport', 4);
INSERT INTO territories VALUES (107, 'East Jeremyberg', 4);
INSERT INTO territories VALUES (108, 'Mckinneyton', 2);
INSERT INTO territories VALUES (109, 'Victoriamouth', 1);
INSERT INTO territories VALUES (110, 'Port Christopher', 2);
INSERT INTO territories VALUES (111, 'New Michael', 3);
INSERT INTO territories VALUES (112, 'Robertton', 2);
INSERT INTO territories VALUES (113, 'East Megan', 3);
INSERT INTO territories VALUES (114, 'New Jenniferbury', 2);
INSERT INTO territories VALUES (115, 'Cherylland', 2);
INSERT INTO territories VALUES (116, 'Stokesfort', 1);
INSERT INTO territories VALUES (117, 'Jeremyfurt', 1);
INSERT INTO territories VALUES (118, 'Taylorview', 4);
INSERT INTO territories VALUES (119, 'Davisland', 4);
INSERT INTO territories VALUES (120, 'Brianside', 4);
INSERT INTO territories VALUES (121, 'Jameshaven', 3);
INSERT INTO territories VALUES (122, 'Colemanburgh', 1);
INSERT INTO territories VALUES (123, 'Lake Lori', 1);
INSERT INTO territories VALUES (124, 'Lake Codyside', 3);
INSERT INTO territories VALUES (125, 'Lake Katrinaberg', 3);
INSERT INTO territories VALUES (126, 'Andersonburgh', 3);
INSERT INTO territories VALUES (127, 'West Vincentland', 3);
INSERT INTO territories VALUES (128, 'East Teresamouth', 1);
INSERT INTO territories VALUES (129, 'North Ashleymouth', 3);
INSERT INTO territories VALUES (130, 'Valenzuelaborough', 3);
INSERT INTO territories VALUES (131, 'Hermanview', 3);
INSERT INTO territories VALUES (132, 'East Cody', 2);
INSERT INTO territories VALUES (133, 'Seanberg', 1);
INSERT INTO territories VALUES (134, 'Jonesview', 4);
INSERT INTO territories VALUES (135, 'Stevenland', 3);
INSERT INTO territories VALUES (136, 'Laurafort', 1);
INSERT INTO territories VALUES (137, 'Port Veronicaside', 3);
INSERT INTO territories VALUES (138, 'Jasminchester', 1);
INSERT INTO territories VALUES (139, 'Lake Aprilburgh', 1);
INSERT INTO territories VALUES (140, 'Jerryside', 4);
INSERT INTO territories VALUES (141, 'New Grace', 2);
INSERT INTO territories VALUES (142, 'Waynefort', 4);
INSERT INTO territories VALUES (143, 'Lauraberg', 4);
INSERT INTO territories VALUES (144, 'Washingtonshire', 3);
INSERT INTO territories VALUES (145, 'North Alejandrastad', 2);
INSERT INTO territories VALUES (146, 'North Rebekah', 4);
INSERT INTO territories VALUES (147, 'Port Arthurview', 2);
INSERT INTO territories VALUES (148, 'Ashleyville', 4);
INSERT INTO territories VALUES (149, 'Port Davidbury', 4);
INSERT INTO territories VALUES (150, 'East Aaron', 2);
INSERT INTO territories VALUES (151, 'South Isabel', 1);
INSERT INTO territories VALUES (152, 'Hannabury', 2);
INSERT INTO territories VALUES (153, 'Port Jesse', 3);
INSERT INTO territories VALUES (154, 'New Scottchester', 2);
INSERT INTO territories VALUES (155, 'Brownborough', 3);
INSERT INTO territories VALUES (156, 'Jamesside', 3);
INSERT INTO territories VALUES (157, 'Whitefort', 1);
INSERT INTO territories VALUES (158, 'South Nicholas', 3);
INSERT INTO territories VALUES (159, 'Jacobtown', 3);
INSERT INTO territories VALUES (160, 'Morrisonstad', 4);
INSERT INTO territories VALUES (161, 'West Kennethport', 1);
INSERT INTO territories VALUES (162, 'Lake Brenda', 4);
INSERT INTO territories VALUES (163, 'Ashleytown', 4);
INSERT INTO territories VALUES (164, 'Wagnerport', 4);
INSERT INTO territories VALUES (165, 'North Johnny', 2);
INSERT INTO territories VALUES (166, 'Lake Kelly', 1);
INSERT INTO territories VALUES (167, 'Thomasfort', 1);
INSERT INTO territories VALUES (168, 'West Shannon', 4);
INSERT INTO territories VALUES (169, 'Buchananburgh', 4);
INSERT INTO territories VALUES (170, 'Port Antoniomouth', 2);
INSERT INTO territories VALUES (171, 'Connerview', 4);
INSERT INTO territories VALUES (172, 'Gonzalesfort', 2);
INSERT INTO territories VALUES (173, 'North Jennifer', 3);
INSERT INTO territories VALUES (174, 'Josephmouth', 4);
INSERT INTO territories VALUES (175, 'Fieldsshire', 4);
INSERT INTO territories VALUES (176, 'Lake Donald', 4);
INSERT INTO territories VALUES (177, 'Erikabury', 2);
INSERT INTO territories VALUES (178, 'Manningtown', 4);
INSERT INTO territories VALUES (179, 'South Regina', 1);
INSERT INTO territories VALUES (180, 'Carriemouth', 2);
INSERT INTO territories VALUES (181, 'East Davidchester', 1);
INSERT INTO territories VALUES (182, 'South Jesse', 2);
INSERT INTO territories VALUES (183, 'Whiteborough', 4);
INSERT INTO territories VALUES (184, 'Lake Amandaside', 4);
INSERT INTO territories VALUES (185, 'Thorntonview', 1);
INSERT INTO territories VALUES (186, 'Lemouth', 2);
INSERT INTO territories VALUES (187, 'Aaronton', 3);
INSERT INTO territories VALUES (188, 'Patrickville', 1);
INSERT INTO territories VALUES (189, 'Hinesview', 4);
INSERT INTO territories VALUES (190, 'Jennifermouth', 1);
INSERT INTO territories VALUES (191, 'Rebeccaberg', 2);
INSERT INTO territories VALUES (192, 'South Dawn', 4);
INSERT INTO territories VALUES (193, 'Joannchester', 4);
INSERT INTO territories VALUES (194, 'Mcintoshmouth', 2);
INSERT INTO territories VALUES (195, 'Burgessstad', 2);
INSERT INTO territories VALUES (196, 'Thomasfurt', 4);
INSERT INTO territories VALUES (197, 'North Anitaborough', 3);
INSERT INTO territories VALUES (198, 'East Jacobtown', 1);
INSERT INTO territories VALUES (199, 'Williamville', 4);
INSERT INTO territories VALUES (200, 'Millerchester', 4);
INSERT INTO territories VALUES (201, 'Michaeltown', 3);
INSERT INTO territories VALUES (202, 'South Ryan', 1);
INSERT INTO territories VALUES (203, 'West Katherineview', 4);
INSERT INTO territories VALUES (204, 'Sandraburgh', 3);
INSERT INTO territories VALUES (205, 'Mitchellside', 1);
